name: Main Regression test
on: push

jobs:
    Regression-test:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout
           uses: actions/checkout@v4
    
         - name: Install Cypress
           run: npm install cypress --save-dev

         - name: Check node version
           run: node -v

         - name: Run Regression tests
           run: npm run headless